#ifndef LREXPORTS_
#define LREXPORTS_

#define LR_SCREENWIDTH 640
#define LR_SCREENHEIGHT 400
#define LR_SCREENASPECT 4/3
#define LR_SCREENFPS 60

#define LR_SOUNDRATE 16000

#define LR_CORENAME "MeowPC98"
#define LR_LIBVERSION "v0.0001"
#define LR_VALIDFILEEXT "hdi"
#define LR_NEEDFILEPATH false
#define LR_BLOCKARCEXTRACT false

#endif
